### ISSUE TITLE
validation screen tutorial should be named "validation screen"

### ISSUE THREAD

**Issue by adriatic** [mattduffield/frontendcreator#12]
- not "navigation screen" as it currently states:

![image](https://user-images.githubusercontent.com/2712405/27445065-876527d8-5746-11e7-966b-a38d84b276cb.png)

**Comment by mattduffield** [comment]
This has been corrected and will be included in the next release! Thanks for the feedback!

**Comment by adriatic** [comment]
Sure - now you know that I am looking at all details I could find. There are some "not easy to express feelings" which I am keeping in mind until finish the tour.

**Comment by adriatic** [comment]
Verified fixed
