### ISSUE TITLE
new project button should be closer to "Manage projects" button

### ISSUE THREAD

**Issue by adriatic** [mattduffield/frontendcreator#16]
![image](https://user-images.githubusercontent.com/2712405/27454450-f25e2762-5767-11e7-9c55-f1806fd66919.png)

The "distance" between the project list and new screen is smaller, but I understand that changing this would disrupt the "visual semantics"

![image](https://user-images.githubusercontent.com/2712405/27455697-32980ad8-576c-11e7-9a46-d3f5565a48ae.png)

**Comment by mattduffield** [comment]
We are currently working on a new UI paradigm that will try to place everything in the same area for consistency and usability. Hope to announce a sneak peak of the visual soon.

**Comment by adriatic** [comment]
I knew that we should expect no less 😄

**Comment by mattduffield** [comment]
This is no longer the case as we now a new navigation panel along with an updated navigation tree that supports creating new folders/files inline.
