### ISSUE TITLE
Cannot log in due to JS error

### ISSUE THREAD

**Issue by steve8708** [mattduffield/frontendcreator#18]
Upon entering my email and password on the login page I just get an infinite loading indicator and can never get into the editor

The console shows this error

```
Uncaught TypeError: Cannot read property 'databases' of undefined
    at e.SessionService.e.preLaunchApp (app-bundle.js:formatted:789)
    at app-bundle.js:formatted:761
    at legacy_api.js:171
    at l.callback (client.js:615)
    at l.<anonymous> (client.js:436)
    at l.r.emit (index.js:133)
    at XMLHttpRequest.e.onreadystatechange (client.js:735)
```

![image](https://user-images.githubusercontent.com/844291/29533408-9a786b06-8666-11e7-9a3b-253395e149a5.png)

**Comment by mattduffield** [comment]
Steve, you need to use the exact link provided. 

http://frontendcreator.com/app/

Let me know if you are still stuck. I will be removing all old accounts this week so this won't be an issue after that.

Best regards,

Matt Duffield 
FrontEnd Creator

**Comment by steve8708** [comment]
ah I see, that worked, thank you!
