### ISSUE TITLE
Docs prev-next links 404

### ISSUE THREAD

**Issue by joshbooker** [mattduffield/frontendcreator#2]
The previous and next links at the bottom of each article are broken in this documentation

**Comment by mattduffield** [comment]
Sorry about that Josh. Please refer to all documentation using the Wiki.

**Comment by joshbooker** [comment]
Thanks Matt. I did not see wiki on mobile version now I see the link. Ps. I sooooo want to use this now!  Any chance of getting into alpha? If so, you can PM me @joshuaabooker thanks and Keep up the great work!
