### ISSUE TITLE
Recursive problem report

### ISSUE THREAD

**Issue by adriatic** [mattduffield/frontendcreator#5]
Please note that the screenshot below shows two problems: the content of the Send Feedback dialog and the failed effort to send that feedback:

![image](https://user-images.githubusercontent.com/2712405/27161147-6621cca2-5147-11e7-9e17-6cf4066b4626.png)

**Comment by mattduffield** [comment]
HI @adriatic,

Thanks for the issue! The issue with the Send Feedback dialog has been corrected and will be in the next release.

We will update the documentation accordingly regarding the avatar as well as work on providing a better UX.

**Comment by adriatic** [comment]
Verified fixed.
